sudo: required
services:
  - docker

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Disable Y/n? confirmation messages on Google Cloud Console
    - GCP_PROJECT_NAME=example-microservices-247217
    - GCP_COMPUTE_ZONE=us-central1-a
    - GCP_CLUSTER_NAME=standard-cluster-1
    - GCP_DEPLOYMENT_NAME=humans
    - DOCKER_IMAGENAME=example-humans

before_install:

  # Travis CLI told me to put this command here to decrypt the service-account.json file I got from GCP.
  # It will temporarily make a file available that provides access to our cluster.
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d

  # Download the cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;

  # Add GCP environment variables to this shell
  - source $HOME/google-cloud-sdk/path.bash.inc

  # Update `kubectl` if necessary
  - gcloud components update kubectl

  # Give google the decrypted service account information
  - gcloud auth activate-service-account --key-file service-account.json

  # Tell google what the project name is
  - gcloud config set project $GCP_PROJECT_NAME

  # Tell google where the project is running
  - gcloud config set compute/zone $GCP_COMPUTE_ZONE

  # Tell google what the cluster name is
  - gcloud container clusters get-credentials $GCP_CLUSTER_NAME

script:
  - echo "no tests to run"

deploy:

  # `Script` means we are on our own
  provider: script

  script: bash ./deploy.sh

  on:
    branch: master